name: GitOpsflow

on:
  push:
    branches:
      - main

jobs:
  build_and_update_manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          version="build-${GITHUB_RUN_NUMBER}"
          echo $version
          docker build -t amith90/todo-app:$version .
          docker push amith90/todo-app:$version

      - name: Update Manifest file
        run: |
          TAG=$((GITHUB_RUN_NUMBER - 1))
          echo "TAG: $TAG"
          git clone https://github.com/Amith90/kube_manifest.git
          cd kube_manifest
          sed -i "s/build-.*/build-$TAG/g" menifest/deployment.yaml
          git config --global user.email "amithkarunaratne@gmail.com"
          git config --global user.name "Amith90"
          git add .
          git commit -m "new build with imgTag build-$TAG"
          git config credential.helper 'cache --timeout=120'
          git push -q https://github.com/Amith90/kube_manifest.git main
